### ISSUE TITLE
Ansible does not install wireguard.

### ISSUE THREAD

**Issue by facastiblancor** [OATS-Group/isoblue-avena#25]
Task **"ensure wireguard key exists"**  from role **"avena-wireguard"** failed with the following error:

`TASK [avena-wireguard : ensure wireguard key exists] ********************************************************************************************************************
fatal: [avena-apalis-dev04]: FAILED! => {"changed": false, "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: '/etc/wireguard'"}
` 
Wireguard was not installed and deployment was halted.

**Comment by facastiblancor** [comment]
Additional to this, it was found that after deployment, the running kernel was Linux 4.19 and not 5.4.

**Comment by abalmos** [comment]
I suspect this is a bug in my attempt to support both `buster` and `testing`. I will look at next week.
