### ISSUE TITLE
Create an app to log received cell signal power to a CSV file.

### ISSUE THREAD

**Issue by facastiblancor** [OATS-Group/isoblue-avena#33]
An app that polls the RSSI power data from ModemManager.

**Comment by abalmos** [comment]
We talked in private about this ... I just wanted to also leave it here that I think we should query DBUS directly for this -- it is quite clean to share the DBUS socket into a container.

Here is the dbus cli version of the requests:

Setting the update rate:
`sudo dbus-send --system --print-reply --dest=org.freedesktop.ModemManager1 /org/freedesktop/ModemManager1/Modem/0 org.freedesktop.ModemManager1.Modem.Signal.Setup uint32:1`

Getting the current values: 
`sudo dbus-send --system --print-reply --dest=org.freedesktop.ModemManager1 /org/freedesktop/ModemManager1/Modem/0 org.freedesktop.DBus.Properties.GetAll string:org.freedesktop.ModemManager1.Modem.Signal`
