### ISSUE TITLE
Missing link in README.md in docs folder

### ISSUE THREAD

**Issue by wang701** [OATS-Group/isoblue-avena#4]
Links for instructions under [Apalis device](https://github.com/OATS-Group/isoblue-avena/blob/ansible/docs/README.md#apalis-v10v11) and [concepts](https://github.com/OATS-Group/isoblue-avena/blob/ansible/docs/README.md#concepts) are dead.

**Comment by wang701** [comment]
Turns out they are not missing. It is using urls which are using the wrong branch and the files are not there. We should use relative links.

**Comment by abalmos** [comment]
They will be right when merged. For now, change the word `master` in the links to `ansible`

**Comment by wang701** [comment]
> They will be right when merged. For now, change the word `master` in the links to `ansible`

Do you think we should use relative links?

**Comment by abalmos** [comment]
Okay, I relative links would be better . Can you leave that on the PR?

**Comment by wang701** [comment]
> Okay, I relative links would be better . Can you leave that on the PR?

Yes.
