### ISSUE TITLE
canwatchdog to container

### ISSUE THREAD

**Issue by abalmos** [OATS-Group/isoblue-avena#51]
# Implementation idea
1. base debian docker image with watchdog script
2. use dbus to issue a `systemd sleep` call
3. use normal canutils to bring up can interfaces --- web service to configure that ... maybe this should be part of the "controller" service.

# Gotchas
1. Need use to host networking mode to access can interfaces

**Comment by facastiblancor** [comment]
This would imply to write CAN-Watchdog from scratch. Which I would prefer to do on Python for portability, and using _libdbus_ to issue the systemd sleep call.

**Comment by abalmos** [comment]
On further thought, I think

> 3. use normal canutils to bring up can interfaces --- web service to configure that ... maybe this should be part of the "controller" service.

belongs in some sort of controller rather then this service ... you may still very well use can without can watchdog.

This script should just watch all paths matching

`/sys/class/net/can*/statistics/rx_bytes`

for dog food.

That said, I *do* think we should include some way of controlling the timeout and easily masking the sleep call ... we really need to figure out what the heck the controller service is.

**Comment by abalmos** [comment]
What if all of our services expose a dbus object / functions? In this case, maybe it is just an object:

- timer `period` in milliseconds
- `enable` boolean to mask / unmask the sleep call


Then our controller service really just manages these service objects / makes DBUS RPC calls

**Comment by abalmos** [comment]
To be clear, I mean we would run an Avena DBUS server (like a user session bus) which would only be accessible by the containers. Exposing the system DBUS would still be a selective "core" service right.

**Comment by facastiblancor** [comment]
I like the idea of having a controller managing all the DBUS service objects and calls, but first we might check if everything we are running right now is compatible with this model, like the loggers. I think the most powerful aspect of running service objects is configuring everything with DBUS, just like NetworkManager and ModemManager.

**Comment by abalmos** [comment]
Right, I think _at least_ anything that would need a config file could use DBUS. I feel like loggers fit that model: what (which cell, which can interface, etc.), rate, where / store.  Maybe a logger broadcasts the data like gpsd does to. That returns some of the original Kafka model.

I think question to answer is: is dbus the right tool for the job?

**Comment by facastiblancor** [comment]
In my opinion, I think that answer depends on the level of abstaction. If we want to move to a fully containerized software release, then interprocess communication is mandatory. Probably a comparison between socket-based communication vs DBUS would help to answer the question. Still I believe NetworkManager's DBUS approach is a good example to follow (without considering the challenges of following this model)
