### ISSUE TITLE
Deploying and Managing Containers

### ISSUE THREAD

**Issue by aaron97neu** [OATS-Group/isoblue-avena#53]
Currently we have no way to manage and deploy docker containers to our Avena devices in the field. In the few instances where I have needed to test containers in the field, I have manually `git clone` the repo and used `docker-compose` to start it manually. This is not elegant or sustainable. 

Possible solutions:
- [Ansible based](https://docs.ansible.com/ansible/latest/modules/docker_compose_module.html): Copy a Docker-Compose file over, possibly using a jinja2 template to configure it. Not elegant, and we are leaning away from using ansible for anything other than the initial deploy
- [k8s](https://kubernetes.io/)/[k3s](https://k3s.io/)/other kubernetes based approach - The Kubernetes model does not map to our model perfectly and would require us to use Kubernetes in a way it was not originally build for
- [BalenaEngine](https://www.balena.io/engine/) - We don't know much about this or if it is applicable, appears to be a souped up `docker-compose` wrapper. Seems more aimed at a docker replacement than a container management tool
- Homebrew custom solution - needs development effort that could be better spent elsewhere

@abalmos Are there any other approaches we discussed that I am missing?

**Comment by aaron97neu** [comment]
Additional options:
- [Docker swarm](https://docs.docker.com/engine/swarm/) - Docker's container management solution. Seems aimed for serving one service and using nodes to support this service which is not the model we want
- [Swarmkit](https://github.com/docker/swarmkit/) - what Docker Swarm is based off of. Might offer more flexibility to force it into our model but would require more development on our end. Same issues with model as Docker swarm
- [Kubedge](https://github.com/kubeedge/kubeedge) - Another edge computing focused Kubernetes platform. Uses MQTT which might be helpful if we choose to use it as our main communication bus as well. No telling how easy it would be to integrate with our MQTT stuff though

None of these have jumped out to me. They all seem to be solving a slightly different problem then ours

In general, it seems most of these services have an inverted model compared to ours - They assume we have a single service/application we want to make available over the internet and the containers are there to support that service. In contrast, we want a single application to be running on each node and just want to manage the deployment of the service. Are we thinking about this wrong/googling for the wrong solutions?

**Comment by aaron97neu** [comment]
We never really identified the requirements for what we need out of a container management system, and this might be why a specific solution does not appear to jump out at us.

As I see it, we are looking for the following features
- Initial container deploy and automated updating as new builds are available on dockerhub/github
  - [Optional] Rollback if things fail
- Ability to tolerate extremely low availability nature of our nodes
- Ability to handle environmental variable based configuration per container like `docker-compose`
  - Handling secrets will be important eventually

Anything else I am missing? If it is this simple I feel like all of the Kubernetes based solutions are quite overpowered

**Comment by abalmos** [comment]
In my opinion, Kubedge is the only one that matches our model

**Comment by abalmos** [comment]
We should also consider / understand [balena-engine](https://github.com/balena-os/balena-engine)

**Comment by aaron97neu** [comment]
I agree that Kubedge seems to be the best solution so far. Balena-engine seems more like a Docker replacement but I have not investigated it significantly
