### ISSUE TITLE
CAN Watchdog "Stay Online" Flag

### ISSUE THREAD

**Issue by aaron97neu** [OATS-Group/isoblue-avena#59]
From meeting with @aultac on 8/7/2020

There should be some sort of flag or mechanism to ask the ISOBlue to stay online even if no CAN is detected. This would be very helpful to keep demos and deploys from being interrupted.

There are several ways we could do this, however containerizing `can-watchdog` may add some complications. Would using DBUS be feasible? 

This likely should be done in conjunction with #51

**Comment by aaron97neu** [comment]
@facastiblancor recommended a simple `sudo systemctl stop can-watchdog.service` and `sudo systemctl start can-watchdog.service` to enable and disable the can watchdog. Wrote up a quick test script and appears to work (250 consecutive successful suspend cycles, alternating with can watchdog enabled and disabled). Will look into adding this as a pre and post task to our ansible scripts. 

The other half of @aultac's suggest was to be able to say "Next time ISOBlue X comes online, I would like it to stay online". This would be very helpful for deploying code to a certain ISOBlue so we don't have to be available when that paticular ISOBlue decides to turn on. This will likely necessitate some sort check to a central server (oats2) every time they turn on. We already have some of this functionality with #61. Maybe this is done as part of #51?

**Comment by abalmos** [comment]
I'm not complaining, but we really need to move forward with containerizing this stuff and solving it in that space. The more we dive into systemd the harder it will be to get out of it. 

I agree that `can-watchdog` should just be a service. I just want to say `docker-compose stop can-watchdog` instead. This requires thought on how we want to expose something like suspend to a container. Should it have the systemd socket (and therefore full control of the system) or should our container manager handle these requests.

Hot take: Do we want to disable `can-watchdog` or do we just want to "digital binky" the ability for the system to _sleep_ at all?

**Comment by aaron97neu** [comment]
Understood, I'll pivot to focusing on containerizing can-watchdog.

I'm unfamiliar with the "digital binky" sleep disable. How does that work and how would I give the container access to it?

**Comment by facastiblancor** [comment]
I think the "digital binky" refers to switching the sleep functionality of `can-watchdog` (@abalmos, correct me if I'm wrong). I also agree it should be a service, but only sending a signal to a "higher-authority" (or manager) to do the systemd calls. Will the manager run also as a container? This is something that confuses me a bit.

**Comment by abalmos** [comment]
> I'm unfamiliar with the "digital binky" sleep disable. How does that work and how would I give the container access to it?

Haha, sorry. Dr. Meyer was famous in ECE for his digital binky. It was in reference to interrupts on microcontrollers. Essentially, a way to say "please ignore this important warning bell until I say it's okay to deal with it", like giving a crying child a binky.

If we have a "higher" power/controller that deals with requests to suspend, restart, etc., it could be given a "binky" setting. In other words, the controller masks all requests to sleep when set and immediately processes them when not.

In this case you would never disable can-watchdog. You would either set the binky bit manually for local work or remotely (with some sort of on-power settings sync) and it would stay awake after power on.

> Will the manager run also as a container

@aaron97neu and I spoke quickly about this two calls ago. We didn't really discuss, but I mentioned my feelings that we should try to make the system read only and containerize everything. Then docker becomes our package manager. By moving system control things into the manager container, we:

1. Provide a means for non-privileged containers to ask for action but also allow for some type of auth/policy layer.
2. Reduce the number of privileged containers needed to get our work done.

That said, this is a really important architecture question and it deserves some thought and discussion.
